using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using RestaurantSoftware.BL_Layer;
using RestaurantSoftware.DA_Layer;
using RestaurantSoftware.Utils;

namespace RestaurantSoftware.P_Layer
{
    public partial class Frm_ThanhToan : DevExpress.XtraEditors.XtraForm
    {
        DataTable dt = new DataTable();
        private Ban_BLL _banBll = new Ban_BLL();
        private ThanhToan_BLL _thanhToanBll = new ThanhToan_BLL();
        private List<int> _listUpdate = new List<int>();
        public bool kt = false;

        public Frm_ThanhToan()
        {
            InitializeComponent();
            dt_NgayLap.Text = DateTime.Now.ToShortDateString();
            // This line of code is generated by Data Source Configuration Wizard
            cmb_NhanVien.Properties.DataSource = new RestaurantSoftware.DA_Layer.RestaurantDBDataContext().NhanViens;
        }


        private void Frm_ThanhToan_Load(object sender, EventArgs e)
        {
            LoadDataSource();

        }
        private void LoadDataSource()
        {
            LoadDsBan();
            _thanhToanBll.LoadHoaDon(grv_HoaDon);
        }
        public void LoadDsBan()
        {
            lvDsBan.Clear();
            DataTable ban = Utils.Utils.ConvertToDataTable<ChiTiet_ThanhToan>(_thanhToanBll.LayDanhSachBan("Chưa thanh toán"));

            lvDsBan.LargeImageList = imageList1;

            foreach (DataRow dr in ban.Rows)
            {
                bool exsistGroup = false;
                ListViewItem lvItem = new ListViewItem();
                ListViewGroup lvGroup = new ListViewGroup();
                lvItem.Text = dr["tenban"].ToString();
                switch (dr["trangthai"].ToString())
                {
                    case "Trống":
                        lvItem.ImageIndex = 2;
                        break;
                    case "Đã đặt":
                        lvItem.ImageIndex = 1;
                        break;
                    case "Đang sử dụng":
                        lvItem.ImageIndex = 0;
                        break;
                }
                lvItem.Name = dr["Idban"].ToString();
                lvGroup.Header = dr["Tenloaiban"].ToString();
                lvItem.Group = lvGroup;

                if (lvDsBan.Groups.Count != 0)
                {
                    foreach (ListViewGroup gr in lvDsBan.Groups)
                    {
                        if (gr.Header == lvGroup.Header)
                        {
                            exsistGroup = true;
                            lvItem.Group = gr;
                            break;
                        }
                    }
                    if (exsistGroup == false)
                    {
                        lvDsBan.Groups.Add(lvGroup);
                    }

                }
                else lvDsBan.Groups.Add(lvGroup);
                lvDsBan.Items.Add(lvItem);

            }
        }

        private void lvDsBan_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (lvDsBan.SelectedItems.Count > 0)
            {
                txt_TenKH.Text = "";
                txt_SDT.Text = "";
                txt_KhachDua.Text = "";
                txt_TraLai.Text = "";
                txt_Ban.Text = lvDsBan.SelectedItems[0].Text;
                _thanhToanBll.loadid(int.Parse(lvDsBan.SelectedItems[0].Name), "Chưa thanh toán", txt_MaHoaDon, cmb_NhanVien, dt_NgayLap,txt_TenKH,txt_SDT);
                _thanhToanBll.LayDsThamSo(txt_VAT, txt_KhuyenMai);
                LoadChiTietHoaDon();
                btn_ThanhToan.Enabled = true;
                checkBoxKhuyenmai.Enabled = true;
                txt_KhachDua.Enabled = true;
                kt = true;


            }
        }
        public void LoadChiTietHoaDon()
        {
            try
            {
                int a = int.Parse(txt_MaHoaDon.Text);
                _thanhToanBll.LoadChiTietHoaDon(a, grd_DanhSachMon);
                TongTien();
                TongHoaDon();
                chuyenvetiente(txt_TongTien);
                chuyenvetiente(txt_TongHoaDon);


            }
            catch (Exception)
            {
                Notifications.Answers("Lỗi load chi tiết");

            }

        }
        public void KiemtraTextBox()
        {
            if (txt_TongTien.Text == "")
            {
                txt_TongTien.Text = "0";
            }
            if (txt_KhuyenMai.Text == "")
            {
                txt_KhuyenMai.Text = "0";
            }
            if (txt_VAT.Text == "")
            {
                txt_VAT.Text = "0";
            }
            if (txt_TongHoaDon.Text == "")
            {
                txt_TongHoaDon.Text = "0";
            }

        }

        private void gv_HoaDon_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            txt_TenKH.Text = "";
            txt_SDT.Text = "";
            txt_KhachDua.Text = "";
            txt_TraLai.Text = "";
            txt_TenKH.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_khachHang);
            txt_MaHoaDon.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_MaHoaDon);
            txt_SDT.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_sdt);
            dt_NgayLap.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_ThoiGian);
            kt = false;
           
            if (gv_HoaDon.GetFocusedRowCellDisplayText(col_TrangThai) == "Đã thanh toán")
            {
                txt_VAT.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_Vat);
                txt_KhuyenMai.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_KhuyenMai);
                btn_ThanhToan.Enabled = false;
                checkBoxKhuyenmai.Enabled = false;
                txt_KhachDua.Enabled = false;

            }
            else
                if (gv_HoaDon.GetFocusedRowCellDisplayText(col_TrangThai) == "Chưa thanh toán")
                {
                    _thanhToanBll.LayDsThamSo(txt_VAT, txt_KhuyenMai);
                    btn_ThanhToan.Enabled = true;
                    checkBoxKhuyenmai.Enabled = true;
                    txt_KhachDua.Enabled = true;

                }

            KiemtraTextBox();
            LoadChiTietHoaDon();
        }

        public void TinhToan()
        {
            try
            {
                TongTien();
                TongHoaDon();
                if (txt_KhachDua.Text != "")
                {
                    int a = chuyenvekieuint(txt_KhachDua);
                    int b = chuyenvekieuint(txt_TongHoaDon);
                    int c = a-b;
                    txt_TraLai.Text = c.ToString();

                }
                chuyenvetiente(txt_TraLai);
            }
            catch (Exception)
            {
                
                
            }
            
        }
        public void chuyenvetiente(TextEdit txt)
        {
            try
            {
                if (txt.Text == "0")
                {
                    int c = int.Parse(txt.Text);
                    txt.Text = c.ToString("0");
                }
                else
                {
                    int c = int.Parse(txt.Text);
                    txt.Text = c.ToString("#,###");
                }
            }
            catch (Exception)
            {


            }
            
            
        }
        public int chuyenvekieuint(TextEdit txt)
        {
            int temp = 0;
            try
            {
                if (txt.Text == "0")
                {
                    int c = int.Parse(txt.Text);
                    temp = int.Parse(c.ToString("0"));
                    return temp;
                }
                else
                {
                    temp  = int.Parse((txt.Text).Replace(",", ""));
                    return temp;
                }
            }
            catch (Exception)
            {

                return temp;
            }
            return temp;

        }
        public void TongTien()
        {
            try
            {
                var a = gv_DanhSachMon.Columns["thanhtien"].SummaryItem.SummaryValue;
                txt_TongTien.EditValue = a;   

            }
            catch (Exception)
            {

                Notifications.Answers("Lỗi tổng tiền");
            }
           
        }

        private void checkBoxKhuyenmai_CheckedChanged(object sender, EventArgs e)
        {

            if (checkBoxKhuyenmai.Checked == true)
            {
                txt_KhuyenMai.Properties.ReadOnly = false;

            }
            else
            {

                txt_KhuyenMai.Properties.ReadOnly = true;
                if (kt == false)
                {
                    if (gv_HoaDon.GetFocusedRowCellDisplayText(col_TrangThai) == "Đã thanh toán")
                    {
                        txt_KhuyenMai.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_KhuyenMai);

                    }
                    else
                        if (gv_HoaDon.GetFocusedRowCellDisplayText(col_TrangThai) == "Chưa thanh toán")
                        {
                            TextEdit a = new TextEdit();
                            _thanhToanBll.LayDsThamSo(a, txt_KhuyenMai);
                        }
                    TinhToan();
                }
                else
                {
                    TextEdit b = new TextEdit();
                    _thanhToanBll.LayDsThamSo(b, txt_KhuyenMai);
                    TinhToan();
                }
            }
         
            
        }

       
        public void TongHoaDon()
        {
            try
            {
                KiemtraTextBox();

                var a = gv_DanhSachMon.Columns["thanhtien"].SummaryItem.SummaryValue;
                int d = Convert.ToInt32(a);
                int b = (d * (int.Parse(txt_VAT.Text))) / 100;
                int c = (d* (int.Parse(txt_KhuyenMai.Text))) / 100;
                txt_TongHoaDon.Text = (d + b - c).ToString();
                chuyenvetiente(txt_TongHoaDon);
                
                
            }
            catch (Exception)
            {

            }

        }

        private void txt_KhuyenMai_EditValueChanged(object sender, EventArgs e)
        {
            if(checkBoxKhuyenmai.Checked ==true)
            {
                //chuyenvekieuint(txt_KhachDua);
                TinhToan();
                //chuyenvetiente(txt_KhachDua);

            }
           

        }

        private void txt_VAT_EditValueChanged(object sender, EventArgs e)
        {
           

        }

        private void txt_KhachDua_EditValueChanged(object sender, EventArgs e)
        {
            TinhToan();
        }

        private void txt_KhachDua_Leave(object sender, EventArgs e)
        {
            chuyenvetiente(txt_KhachDua);
          
            chuyenvetiente(txt_TongHoaDon);
        }

        private void txt_KhachDua_Click(object sender, EventArgs e)
        {
            txt_KhachDua.Text = "";
            txt_TraLai.Text = "";
        }

        private void btn_ThanhToan_Click(object sender, EventArgs e)
        {

            string a = (txt_TongHoaDon.Text).Replace(",","");
            HoaDonThanhToan hd = new HoaDonThanhToan();
            hd.id_hoadon = int.Parse(txt_MaHoaDon.Text);
            hd.khuyenmai = int.Parse(txt_KhuyenMai.Text);
            hd.vat = int.Parse(txt_VAT.Text);
            hd.tongtien = int.Parse(a);
            hd.trangthai = "Đã thanh toán";
            Ban bn = new Ban();
            bn.id_ban = int.Parse(lvDsBan.SelectedItems[0].Name);
            bn.trangthai = "Trống";
            _thanhToanBll.ThanhToan(hd);
            _banBll.CapNhatBanThanhToan(bn);
            Notifications.Answers("Thanh toán thành công!");
            LoadDataSource();
        }


    }
}