using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using RestaurantSoftware.BL_Layer;
using RestaurantSoftware.DA_Layer;

namespace RestaurantSoftware.P_Layer
{
    public partial class Frm_PhucVu : DevExpress.XtraEditors.XtraForm
    {
        PhucVu_BLL phucvu_bll = new PhucVu_BLL();
        KhachHang_BLL kh_bll = new KhachHang_BLL();
        public Frm_PhucVu()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            //txt_TenKH.Properties.DataSource = new RestaurantSoftware.DA_Layer.RestaurantDBDataContext().KhachHangs;
        }
        private void Frm_PhucVu_Load(object sender, EventArgs e)
        {
            LoadDataSource();
            LoadDsKhachHang();
        }
        private void LoadDataSource()
        {
            LoadDsBan();
            
        }
        public void LoadDsBan()
        {
            lvDsBan.Clear();
            DataTable ban = Utils.Utils.ConvertToDataTable<Ban>(phucvu_bll.LayDanhSachBan());

            lvDsBan.LargeImageList = imageList1;

            foreach (DataRow dr in ban.Rows)
            {
                bool exsistGroup = false;
                ListViewItem lvItem = new ListViewItem();
                ListViewGroup lvGroup = new ListViewGroup();
                lvItem.Text = dr["tenban"].ToString();
                switch (dr["trangthai"].ToString())
                {
                    case "Trống":
                        lvItem.ImageIndex = 2;
                        break;
                    case "Đã đặt":
                        lvItem.ImageIndex = 1;
                        break;
                    case "Đang sử dụng":
                        lvItem.ImageIndex = 0;
                        break;
                }
                lvItem.Name = dr["id_ban"].ToString();
                lvGroup.Header = ((LoaiBan)dr[6]).tenloaiban; 
                lvItem.Group = lvGroup;

                if (lvDsBan.Groups.Count != 0)
                {
                    foreach (ListViewGroup gr in lvDsBan.Groups)
                    {
                        if (gr.Header == lvGroup.Header)
                        {
                            exsistGroup = true;
                            lvItem.Group = gr;
                            break;
                        }
                    }
                    if (exsistGroup == false)
                    {
                        lvDsBan.Groups.Add(lvGroup);
                    }

                }
                else lvDsBan.Groups.Add(lvGroup);
                lvDsBan.Items.Add(lvItem);

            }
        }
        public void LoadDsKhachHang()
        {
            DataTable dt = Utils.Utils.ConvertToDataTable<KhachHang>(kh_bll.LayDanhSachKhachHang());
            cmb_KhachHang.Properties.DataSource = dt;
            cmb_KhachHang.Properties.DisplayMember = "tenkh";
            cmb_KhachHang.Properties.ValueMember = "id_khachhang";
        }
        private void lvDsBan_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (lvDsBan.SelectedItems.Count > 0)
            {
                txt_Ban.Text = lvDsBan.SelectedItems[0].Text;
                phucvu_bll.loadid(int.Parse(lvDsBan.SelectedItems[0].Name),"Chưa thanh toán", txt_MaHoaDon, cmb_NhanVien, dt_NgayLap,cmb_KhachHang);
    
            }
        }

        private void cmb_KhachHang_EditValueChanged(object sender, EventArgs e)
        {
            DevExpress.XtraEditors.LookUpEdit editor = (sender as DevExpress.XtraEditors.LookUpEdit);
            DataRowView row = editor.Properties.GetDataSourceRowByKeyValue(editor.EditValue) as DataRowView;
            txt_SDT.Text = row["sdt"].ToString();
        }


       

    }
}