using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using RestaurantSoftware.BL_Layer;
using RestaurantSoftware.Utils;
using RestaurantSoftware.DA_Layer;

namespace RestaurantSoftware.P_Layer
{
    public partial class Frm_HoaDon : DevExpress.XtraEditors.XtraForm
    {
        DataTable dt = new DataTable();
        private Ban_BLL _banBll = new Ban_BLL();
        private ThanhToan_BLL _thanhToanBll = new ThanhToan_BLL();
        private HoaDon_BLL HoaDon_Bll = new HoaDon_BLL();
        private List<int> _listUpdate = new List<int>();
        public Frm_HoaDon()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            cmb_NhanVien.Properties.DataSource = new RestaurantSoftware.DA_Layer.RestaurantDBDataContext().NhanViens;
        }
         private void LoadDataSource()
        {
            HoaDon_Bll.LoadHoaDon(grv_HoaDon);
        }
         private void Frm_HoaDon_Load(object sender, EventArgs e)
         {
             dt_NgayLap.Text = DateTime.Now.ToShortDateString();
             LoadDataSource();

         }
       
        public void LoadChiTietHoaDon()
        {
            try
            {
                int a = int.Parse(txt_MaHoaDon.Text);
                _thanhToanBll.LoadChiTietHoaDon(a, grd_DanhSachMon);
                var b = gv_DanhSachMon.Columns["thanhtien"].SummaryItem.SummaryValue;
                txt_TongTien.EditValue = b; 
               

            }
            catch (Exception)
            {
                Notifications.Answers("Lỗi load chi tiết");

            }

        }
        public void KiemtraTextBox()
        {
            if (txt_TongTien.Text == "")
            {
                txt_TongTien.Text = "0";
            }
            if (txt_KhuyenMai.Text == "")
            {
                txt_KhuyenMai.Text = "0";
            }
            if (txt_VAT.Text == "")
            {
                txt_VAT.Text = "0";
            }
            if (txt_TongHoaDon.Text == "")
            {
                txt_TongHoaDon.Text = "0";
            }

        }

        private void gv_HoaDon_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            txt_TenKH.Text = "";
            txt_SDT.Text = "";
            txt_TenKH.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_khachHang);
            cmb_NhanVien.EditValue = int.Parse(gv_HoaDon.GetFocusedRowCellDisplayText(col_nhanvien));
            txt_Ban.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_TenBan);
            txt_MaHoaDon.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_MaHoaDon);
            txt_SDT.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_sdt);
            dt_NgayLap.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_ThoiGian);
            txt_VAT.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_Vat);
            txt_KhuyenMai.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_KhuyenMai);
            int temp = Convert.ToInt32(gv_HoaDon.GetFocusedRowCellDisplayText(col_TongHoaDon));
            txt_TongHoaDon.Text = temp.ToString("#,###");
            KiemtraTextBox();
            LoadChiTietHoaDon();
        }

        private void btn_Xoa_Click(object sender, EventArgs e)
        {
            DialogResult dlr = MessageBox.Show("Bạn có chắc chắn muốn xóa hóa đơn này!", "THÔNG BÁO", MessageBoxButtons.YesNoCancel, MessageBoxIcon.Question);
            if (dlr == DialogResult.Yes)
            {
                HoaDonThanhToan qd = new HoaDonThanhToan();
                qd.id_hoadon = int.Parse(txt_MaHoaDon.Text);
                qd.trangthai = "Hủy";
                HoaDon_Bll.CapNhatHoaDon(qd);
                Notifications.Answers("Xóa thành công!");
                Frm_HoaDon_Load(sender, e);
            }
            else
                Notifications.Answers("Xóa không thành công!");

           
        }

      
    }
}