using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using RestaurantSoftware.BL_Layer;
using RestaurantSoftware.Utils;

namespace RestaurantSoftware.P_Layer
{
    public partial class Frm_HoaDon : DevExpress.XtraEditors.XtraForm
    {
        DataTable dt = new DataTable();
        private Ban_BLL _banBll = new Ban_BLL();
        private ThanhToan_BLL _thanhToanBll = new ThanhToan_BLL();
        private HoaDon_BLL HoaDon_Bll = new HoaDon_BLL();
        private List<int> _listUpdate = new List<int>();
        public bool kt = false;
        public Frm_HoaDon()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            cmb_NhanVien.Properties.DataSource = new RestaurantSoftware.DA_Layer.RestaurantDBDataContext().NhanViens;
        }
         private void LoadDataSource()
        {
            HoaDon_Bll.LoadHoaDon(grv_HoaDon);
        }
         private void Frm_HoaDon_Load(object sender, EventArgs e)
         {
             dt_NgayLap.Text = DateTime.Now.ToShortDateString();
             LoadDataSource();

         }
       
        public void LoadChiTietHoaDon()
        {
            try
            {
                int a = int.Parse(txt_MaHoaDon.Text);
                _thanhToanBll.LoadChiTietHoaDon(a, grd_DanhSachMon);
                TongTien();
                TongHoaDon();
                chuyenvetiente(txt_TongTien);
                chuyenvetiente(txt_TongHoaDon);


            }
            catch (Exception)
            {
                Notifications.Answers("Lỗi load chi tiết");

            }

        }
        public void KiemtraTextBox()
        {
            if (txt_TongTien.Text == "")
            {
                txt_TongTien.Text = "0";
            }
            if (txt_KhuyenMai.Text == "")
            {
                txt_KhuyenMai.Text = "0";
            }
            if (txt_VAT.Text == "")
            {
                txt_VAT.Text = "0";
            }
            if (txt_TongHoaDon.Text == "")
            {
                txt_TongHoaDon.Text = "0";
            }

        }

        private void gv_HoaDon_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            txt_TenKH.Text = "";
            txt_SDT.Text = "";
            txt_KhachDua.Text = "";
            txt_TraLai.Text = "";
            txt_TenKH.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_khachHang);
            cmb_NhanVien.EditValue = int.Parse(gv_HoaDon.GetFocusedRowCellDisplayText(col_nhanvien));
            txt_Ban.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_TenBan);
            txt_MaHoaDon.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_MaHoaDon);
            txt_SDT.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_sdt);
            dt_NgayLap.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_ThoiGian);
            kt = false;
           
            if (gv_HoaDon.GetFocusedRowCellDisplayText(col_TrangThai) == "Đã thanh toán")
            {
                txt_VAT.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_Vat);
                txt_KhuyenMai.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_KhuyenMai);
                btn_ThanhToan.Enabled = false;
                checkBoxKhuyenmai.Enabled = false;
                txt_KhachDua.Enabled = false;

            }
            else
                if (gv_HoaDon.GetFocusedRowCellDisplayText(col_TrangThai) == "Chưa thanh toán")
                {
                    _thanhToanBll.LayDsThamSo(txt_VAT, txt_KhuyenMai);
                    txt_KhachDua.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_DaTra);

                    btn_ThanhToan.Enabled = true;
                    checkBoxKhuyenmai.Enabled = true;
                    txt_KhachDua.Enabled = true;

                }

            KiemtraTextBox();
            LoadChiTietHoaDon();
        }

        public void TinhToan()
        {
            try
            {
                TongTien();
                TongHoaDon();
                if (txt_KhachDua.Text != "")
                {
                    int a = chuyenvekieuint(txt_KhachDua);
                    int b = chuyenvekieuint(txt_TongHoaDon);
                    int c = a-b;
                    txt_TraLai.Text = c.ToString();

                }
                chuyenvetiente(txt_TraLai);
            }
            catch (Exception)
            {
                
                
            }
            
        }
        public void chuyenvetiente(TextEdit txt)
        {
            try
            {
                if (txt.Text == "0")
                {
                    int c = int.Parse(txt.Text);
                    txt.Text = c.ToString("0");
                }
                else
                {
                    int c = int.Parse(txt.Text);
                    txt.Text = c.ToString("#,###");
                }
            }
            catch (Exception)
            {


            }
            
            
        }
        public int chuyenvekieuint(TextEdit txt)
        {
            int temp = 0;
            try
            {
                if (txt.Text == "0")
                {
                    int c = int.Parse(txt.Text);
                    temp = int.Parse(c.ToString("0"));
                    return temp;
                }
                else
                {
                    temp  = int.Parse((txt.Text).Replace(",", ""));
                    return temp;
                }
            }
            catch (Exception)
            {

                return temp;
            }
            return temp;

        }
        public void TongTien()
        {
            try
            {
                var a = gv_DanhSachMon.Columns["thanhtien"].SummaryItem.SummaryValue;
                txt_TongTien.EditValue = a;   

            }
            catch (Exception)
            {

                Notifications.Answers("Lỗi tổng tiền");
            }
           
        }

        private void checkBoxKhuyenmai_CheckedChanged(object sender, EventArgs e)
        {

            if (checkBoxKhuyenmai.Checked == true)
            {
                txt_KhuyenMai.Properties.ReadOnly = false;

            }
            else
            {

                txt_KhuyenMai.Properties.ReadOnly = true;
                if (kt == false)
                {
                    if (gv_HoaDon.GetFocusedRowCellDisplayText(col_TrangThai) == "Đã thanh toán")
                    {
                        txt_KhuyenMai.Text = gv_HoaDon.GetFocusedRowCellDisplayText(col_KhuyenMai);

                    }
                    else
                        if (gv_HoaDon.GetFocusedRowCellDisplayText(col_TrangThai) == "Chưa thanh toán")
                        {
                            TextEdit a = new TextEdit();
                            _thanhToanBll.LayDsThamSo(a, txt_KhuyenMai);
                        }
                    TinhToan();
                }
                else
                {
                    TextEdit b = new TextEdit();
                    _thanhToanBll.LayDsThamSo(b, txt_KhuyenMai);
                    TinhToan();
                }
            }
         
            
        }

       
        public void TongHoaDon()
        {
            try
            {
                KiemtraTextBox();

                var a = gv_DanhSachMon.Columns["thanhtien"].SummaryItem.SummaryValue;
                int d = Convert.ToInt32(a);
                int b = (d * (int.Parse(txt_VAT.Text))) / 100;
                int c = (d* (int.Parse(txt_KhuyenMai.Text))) / 100;
                txt_TongHoaDon.Text = (d + b - c).ToString();
                chuyenvetiente(txt_TongHoaDon);
                
                
            }
            catch (Exception)
            {

            }

        }

        private void txt_KhuyenMai_EditValueChanged(object sender, EventArgs e)
        {
            if (checkBoxKhuyenmai.Checked == true)
            {
                //chuyenvekieuint(txt_KhachDua);
                TinhToan();
                //chuyenvetiente(txt_KhachDua);

            }

        }

      
    }
}