using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using RestaurantSoftware.BL_Layer;
using RestaurantSoftware.DA_Layer;
using RestaurantSoftware.Utils;

namespace RestaurantSoftware.P_Layer
{
    public partial class Frm_SuCo : DevExpress.XtraEditors.XtraForm
    {
        DataTable dt = new DataTable();
        private SuCo_BLL _sucoBLL = new SuCo_BLL();
        private List<int> _listUpdate = new List<int>();
        DateTime today = DateTime.Today;
        FormMain fr = new FormMain();
        string kt = "Them";
        int ID_NHANVIEN = 0;
        int idSuCoSelected = 0;
        public Frm_SuCo(int idnv)
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizarde
            cmb_NhanVienLap.Properties.DataSource = new RestaurantSoftware.DA_Layer.RestaurantDBDataContext().NhanViens;
            // This line of code is generated by Data Source Configuration Wizard
            ID_NHANVIEN = idnv;
            cmb_NhanVienLap.EditValue = ID_NHANVIEN;
        }
        private void Frm_SuCo_Load(object sender, EventArgs e)
        {
            LoadDataSource();
            dt_NgayLap.Text = DateTime.Now.ToShortDateString();
            LoadDsKhachHang();
        }
        private void LoadDataSource()
        {
            _sucoBLL.LayDanhSachSuCo(gridControl1);


        }
        public void LoadDsKhachHang()
        {
            DataTable dt = Utils.Utils.ConvertToDataTable<KhachHang>(_sucoBLL.LayDsKhachHang());
            cmb_TenKhachHang.Properties.DataSource = dt;
            cmb_TenKhachHang.Properties.DisplayMember = "tenkh";
            cmb_TenKhachHang.Properties.ValueMember = "id_khachhang";
        }

        private void gv_SuCo_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            txt_MaSuCo.Text = gv_SuCo.GetFocusedRowCellDisplayText(col_MaSuCo);
            txt_TenSuCo.Text = gv_SuCo.GetFocusedRowCellDisplayText(col_TenSuCo);
            string a = gv_SuCo.GetFocusedRowCellDisplayText(col_NhanVien);
            cmb_NhanVienLap.EditValue = int.Parse(a);
            dt_NgayLap.DateTime = Convert.ToDateTime(gv_SuCo.GetFocusedRowCellDisplayText(col_NgayLap));
            rxt_NoiDung.Text = gv_SuCo.GetFocusedRowCellDisplayText(col_NoiDung);
            string b = gv_SuCo.GetFocusedRowCellDisplayText(col_KhachHang);
            cmb_TenKhachHang.EditValue = int.Parse(b);
            kt = "Sua";
        }



        private void cmb_TenKhachHang_EditValueChanged_1(object sender, EventArgs e)
        {
            DevExpress.XtraEditors.LookUpEdit editor = (sender as DevExpress.XtraEditors.LookUpEdit);
            DataRowView row = editor.Properties.GetDataSourceRowByKeyValue(editor.EditValue) as DataRowView;
            txt_SoDienThoai.Text = row["sdt"].ToString();
            txt_DiaChi.Text = row["diachi"].ToString();
        }
        public void ReLoadSuCo()
        {
            int c = Convert.ToInt32(cmb_TenKhachHang.EditValue);
            var query = _sucoBLL.LoadSuCo(txt_TenSuCo.Text, today,c);
                foreach(var i in query)
                {
                    idSuCoSelected = i.id_suco;
                    txt_MaSuCo.Text = i.id_suco.ToString();
                }
        }
        private void btn_Luu_Click(object sender, EventArgs e)
        {
            if (kt == "Them")
            {
                if (txt_TenSuCo.Text != "")
                {
                    SuCo qd = new SuCo();
                    qd.tensuco = txt_TenSuCo.Text;
                    qd.id_nhanvien = (int)cmb_NhanVienLap.EditValue;
                    qd.ngaylap = dt_NgayLap.DateTime;
                    qd.noidung = rxt_NoiDung.Text;
                    qd.id_khachhang = (int)cmb_TenKhachHang.EditValue;
                    _sucoBLL.ThemSuCo(qd);
                    Notifications.Answers("Thêm thành công!");
                    ReLoadSuCo();
                    LoadDataSource();
                }
                else
                    Notifications.Answers("Bạn chưa nhập tên sự cố.");

                


            }
            else
                if (kt == "Sua")
                {
                    if (txt_TenSuCo.Text != "")
                    {
                    SuCo qd = new SuCo();
                    qd.id_suco = int.Parse(txt_MaSuCo.Text);
                    qd.tensuco = txt_TenSuCo.Text;
                    qd.id_nhanvien = (int)cmb_NhanVienLap.EditValue;
                    qd.ngaylap = dt_NgayLap.DateTime;
                    qd.noidung = rxt_NoiDung.Text;
                    qd.id_khachhang = (int)cmb_TenKhachHang.EditValue;
                    _sucoBLL.CapNhatSuCo(qd);
                    Notifications.Answers("Sửa thành công!");
                    LoadDataSource();

                   }
                    else
                        Notifications.Answers("Bạn chưa nhập tên sự cố.");

              }
        }

        private void btn_Xoa_Click(object sender, EventArgs e)
        {
             DialogResult dlr = MessageBox.Show("Bạn có chắc chắn muốn xóa sự cố này!", "THÔNG BÁO", MessageBoxButtons.YesNoCancel, MessageBoxIcon.Question);
                if (dlr == DialogResult.Yes)
                {
                    try
                    {
               
                            _sucoBLL.XoaSuCo(int.Parse(txt_MaSuCo.Text));
                            Notifications.Answers("Xóa thành công!");
                            btn_LamMoi_Click(sender, e);
                            LoadDataSource();
                    }
                    catch (Exception)
                    {

                        Notifications.Answers("Bạn chưa chọn sự cố để xóa");
                    }
                }
                else
                    Notifications.Answers("Xóa không thành công!");
           
        }

        private void btn_LamMoi_Click(object sender, EventArgs e)
        {
            txt_MaSuCo.Text = "";
            txt_TenSuCo.Text = "";
            dt_NgayLap.Text = DateTime.Now.ToShortDateString();
            rxt_NoiDung.Text = "";
            kt = "Them";
            cmb_NhanVienLap.EditValue = ID_NHANVIEN;
            LoadDataSource();
        }

        private void btn_In_Click(object sender, EventArgs e)
        {
            try
            {
                PrintfSuCo sc = new PrintfSuCo(int.Parse(txt_MaSuCo.Text));
                sc.Show();
            }
            catch (Exception)
            {
                
                Notifications.Answers(" Bạn chưa chọn sự cố để in");
            }
           
        }
    }
}